In [3]:
import pandas as pd
import numpy as np
import xgboost as xgb

In [22]:
train=pd.read_pickle("/disk3/zk/aboutoil/Shengli/data/4-training_data/shallow_methods/xgboost_train_data_76d.pkl")
test=pd.read_pickle("/disk3/zk/aboutoil/Shengli/data/4-training_data/shallow_methods/xgboost_test_data_76d.pkl")
val=pd.read_pickle("/disk3/zk/aboutoil/Shengli/data/4-training_data/shallow_methods/xgboost_val_data_76d.pkl")

In [23]:
train[0].shape

(30678, 76)

In [24]:
len(train)

2

In [25]:
train[0]

array([[ 1.11783143, -0.21322035, -0.9022795 , ...,  0.65215143,
         0.69893747,  0.14812079],
       [ 1.25830374,  1.11090515, -0.86646311, ...,  0.64271013,
         0.80539448,  0.25612106],
       [ 1.40994237,  1.38857296, -0.5076096 , ...,  0.63775027,
         0.87679584,  0.41226204],
       ...,
       [ 2.84861994,  2.37890235,  2.27180222, ...,  1.63916119,
         1.47462839,  2.81047636],
       [ 2.89480051,  2.57008148,  2.32248963, ...,  1.68164932,
         1.55622598,  2.58006158],
       [ 2.93243394,  2.64821319,  2.36132522, ...,  1.7241627 ,
         1.68116902,  3.01140082]])

In [26]:
train[1]

array([0., 0., 0., ..., 0., 0., 0.])

In [27]:
len(test[2].keys())

21

In [28]:
test


(array([[ 0.76031799, -1.60426558, -0.51917572, ...,  0.31288807,
         -0.22658083,  2.05358877],
        [ 0.73176924, -1.77015547, -0.61262998, ...,  0.30233323,
         -0.165528  ,  1.42604201],
        [ 0.59527371, -1.7756132 , -0.62017819, ...,  0.30141826,
         -0.0037065 ,  1.37404967],
        ...,
        [-2.11555491,  1.18543851,  1.18017485, ...,  0.85494565,
          0.84204667,  1.33825565],
        [-2.10483357, -0.10079794,  1.13333703, ...,  0.81623881,
          0.88602094,  1.93028759],
        [-1.77408804, -0.64174942,  1.08505427, ...,  0.77424293,
          0.91555972,  2.36511371]]),
 array([0., 1., 1., ..., 0., 0., 0.]),
 {'CB81': [array([[ 0.76031799, -1.60426558, -0.51917572, ...,  0.31288807,
           -0.22658083,  2.05358877],
          [ 0.73176924, -1.77015547, -0.61262998, ...,  0.30233323,
           -0.165528  ,  1.42604201],
          [ 0.59527371, -1.7756132 , -0.62017819, ...,  0.30141826,
           -0.0037065 ,  1.37404967],
        